name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  
          
      - name: Setup Node
        uses: actions/setup-node@v3
        
      - run: npm install && npm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: dist
